#!/usr/bin/env python
from __future__ import print_function
import hashlib, time, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
MANIFEST=ROOT/'PACKAGE_MANIFEST.md'
EXCLUDE_DIRS={'.git','dist','reports','__pycache__','.pytest_cache','.mypy_cache','.ruff_cache'}
EXCLUDE_FILES={'PACKAGE_MANIFEST.md'}
def include(p):
    rel=p.relative_to(ROOT)
    if any(part in EXCLUDE_DIRS for part in rel.parts): return False
    if p.name in EXCLUDE_FILES: return False
    return p.is_file()
def sha256(p):
    h=hashlib.sha256();
    with p.open('rb') as f:
        for b in iter(lambda:f.read(65536), b''): h.update(b)
    return h.hexdigest()
def main():
    files=[p for p in sorted(ROOT.rglob('*')) if include(p)]
    body=[]
    body.append('---')
    body.append('document_id: DOC-000-MANIFEST')
    body.append('title: "Package Manifest"')
    body.append('version: 0.2.0')
    body.append('revision: REV-002')
    body.append('status: DRAFT-REFERENCE')
    body.append('last_updated: 2026-05-16')
    body.append('package_id: 20260516_00_seed')
    body.append('machine_reference_prefix: DOC-000-MANIFEST')
    body.append('normative_status: Normative')
    body.append('source: "Generated by tools/manifest_update.py"')
    body.append('---\n')
    body.append('# Package Manifest\n')
    body.append('Generated by `python tools/manifest_update.py`. Runtime audit reports under `reports/` are intentionally excluded because they are regenerated during diagnostics.\n')
    body.append('| Path | Size Bytes | SHA256 |')
    body.append('|---|---:|---|')
    for p in files:
        rel=p.relative_to(ROOT).as_posix()
        body.append('| `%s` | %d | `%s` |' % (rel, p.stat().st_size, sha256(p)))
    MANIFEST.write_text('\n'.join(body)+'\n', encoding='utf-8')
    print('updated %s with %d files' % (MANIFEST, len(files)))
    return 0
if __name__=='__main__': sys.exit(main())
